### ISSUE TITLE
Game crashes when loading into new lscene

### ISSUE THREAD

**Issue by Aerotactics** [Virshal/bw-instant-death#1]
When the health mod is enabled, and you load a new scene, the game crashes about 2 seconds after loading in.

**Comment by Aerotactics** [comment]
Possible fix:
`
// OnSceneLoaded
    TryGetPlayerHealth();
    
//
async void TryGetPlayerHealth
{
    await(100);
    playerHealth = GameObject.FindObjectOfType<Player_Health>();
    if(playerHealth == null)
        TryGetPlayerHealth()
    else
        UpdateSettings()
}

`

**Comment by Fizzyhex** [comment]
Now fixed in the latest version. Thanks!

**Comment by Aerotactics** [comment]
I can confirm that update fixed the crashing, and the mod is working as intended.
